const navCategoryForMakerStudio = {
    category: [
        {
            name: "funding",
            title: "펀딩 준비",
            optionZero: "기본 요건",
            optionZeroId: "screening",
            optionOne: "기본 정보",
            optionOneId: "baseinfo",
            optionTwo: "스토리 작성",
            optionTwoId: "story",
            optionThree: "리워드 설계",
            optionThreeId: "condition",
            optionFour: "위험요인 및 정책",
            optionFourId: "policy",
            optionFive: "메이커 정보",
            optionFIveId: "makerInfo",
            unlock: true
        },
        {
            name: "list2",
            title: "오픈예정 현황",
            optionZero: "",
            optionZeroId: "",
            optionOne: "",
            optionOneId: "",
            optionTwo: "",
            optionTwoId: "",
            optionThree: "",
            optionThreeId: "",
            optionFour: "",
            optionFourId: "",
            optionFive: "",
            optionFIveId: "",
            unlock: false
        },
        {
            name: "list3",
            title: "편딩 현황",
            optionZero: "",
            optionZeroId: "",
            optionOne: "",
            optionOneId: "",
            optionTwo: "",
            optionTwoId: "",
            optionThree: "",
            optionThreeId: "",
            optionFour: "",
            optionFourId: "",
            optionFive: "",
            optionFIveId: "",
            unlock: false
        },
        {
            name: "list4",
            title: "결제 현황",
            optionZero: "",
            optionZeroId: "",
            optionOne: "",
            optionOneId: "",
            optionTwo: "",
            optionTwoId: "",
            optionThree: "",
            optionThreeId: "",
            optionFour: "",
            optionFourId: "",
            optionFive: "",
            optionFIveId: "",
            unlock: false
        },
        {
            name: "list5",
            title: "서포터",
            optionZero: "",
            optionZeroId: "",
            optionOne: "",
            optionOneId: "",
            optionTwo: "",
            optionTwoId: "",
            optionThree: "",
            optionThreeId: "",
            optionFour: "",
            optionFourId: "",
            optionFive: "",
            optionFIveId: "",
            unlock: false
        },
        {
            name: "list6",
            title: "자료 및 도움말",
            optionZero: "",
            optionZeroId: "",
            optionOne: "",
            optionOneId: "",
            optionTwo: "",
            optionTwoId: "",
            optionThree: "",
            optionThreeId: "",
            optionFour: "",
            optionFourId: "",
            optionFive: "",
            optionFIveId: "",
            unlock: true
        }
    ],
    list1:
    {
        name: "funding",
        title: "펀딩 준비",
        optionZero: "기본 요건",
        optionOne: "기본 정보",
        optionTwo: "스토리 작성",
        optionThree: "리워드 설계",
        optionFour: "위험요인 및 정책",
        optionFive: "메이커 정보",
    }
}


export default navCategoryForMakerStudio